### ISSUE TITLE
空指针异常com.miot.common.people.People.getUserId

### ISSUE THREAD

**Issue by hhcc1992** [MiEcosystem/mijiaSDK#22]
有时候会sdk内部会偶发com.miot.common.people.People.getUserId的空指针异常
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.miot.common.people.Account.getUserId()' on a null object reference
       at com.miot.common.people.People.getUserId(SourceFile)
       at com.miot.service.manager.discovery.impl.DeviceFactory.createFrom(SourceFile)
       at com.miot.service.common.manager.ServiceManager$AccountManager$1.run(SourceFile)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
![image](https://user-images.githubusercontent.com/38647981/53217504-29269e80-3693-11e9-90c8-039a0f8d9858.png)
![image](https://user-images.githubusercontent.com/38647981/53217524-3e033200-3693-11e9-911a-bb3bab6a7289.png)
![80e2cc93-f6de-436c-8a6e-4eb43f8c0267](https://user-images.githubusercontent.com/38647981/53217617-a18d5f80-3693-11e9-9f14-3917678b9777.png)

**Comment by M201370367** [comment]
mijiaSDK不要做混淆，如果涉及OTA升级，检查下OTA前后是不是做了混淆处理。
