### ISSUE TITLE
选择wifi界面崩溃log

### ISSUE THREAD

**Issue by hudson-s** [MiEcosystem/mijiaSDK#23]
Process: com.chuangmi.imihome:miot, PID: 18750
    java.lang.RuntimeException: Unable to destroy activity {com.chuangmi.imihome/com.miot.service.connection.wifi.SmartConfigMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4505)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
        at com.miot.service.connection.DeviceConnectionImpl.getBase64(DeviceConnectionImpl.java:152)
        at com.miot.service.connection.DeviceConnectionImpl.access$000(DeviceConnectionImpl.java:29)
        at com.miot.service.connection.DeviceConnectionImpl$1.onSucceed(DeviceConnectionImpl.java:92)
        at com.miot.service.connection.wifi.SmartConfigMainActivity.onDestroy(SmartConfigMainActivity.java:190)
        at android.app.Activity.performDestroy(Activity.java:7252)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4492)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by M201370367** [comment]
确认下，该问题是必现的吗？必现的话是什么场景下必现？

**Comment by hudson-s** [comment]
必现问题，选择wifi界面 退出 再进，退出再进   getQrCode函数

**Comment by M201370367** [comment]
好的，本周会fix该Issue

**Comment by M201370367** [comment]
您好，上周五已更新米家SDK 3.3.11：
https://github.com/MiEcosystem/mijiaSDK/tree/stable3.0/controller/android
