### ISSUE TITLE
账号登陆的情况下，绑定设备崩溃

### ISSUE THREAD

**Issue by Chgocn** [MiEcosystem/mijiaSDK#6]
java.lang.NumberFormatException: For input string: ""
        at java.lang.Long.parseLong(Long.java:455)
        at java.lang.Long.valueOf(Long.java:542)
        at com.miot.service.connection.wifi.b.c.a(BleComboStep.java:686)
        at com.miot.service.connection.wifi.b.c.j(BleComboStep.java:645)
        at com.miot.service.connection.wifi.b.c.a(BleComboStep.java:129)
        at com.miot.service.connection.wifi.SmartConfigMainActivity$1.handleMessage(SmartConfigMainActivity.java:48)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6359)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by wangchongwhut** [comment]
已修复
