### ISSUE TITLE
Property中dataType定义为float类型，解析崩溃（Double 类型无法转换成 Float）

### ISSUE THREAD

**Issue by Chgocn** [MiEcosystem/mijiaSDK#7]
版本：mijiaClient-3-3-2.aar,mijiaService-3-3-2.aar,mijiaBluetooth-3-3-2.aar,codegenerator-3-3-0.jar
错误日志：
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
        at com.miot.common.property.AllowedValueRange.isValueValid(AllowedValueRange.java:80)
        at com.miot.common.property.AllowedValue.isValid(AllowedValue.java:14)
        at com.miot.common.property.PropertyDefinition.validate(PropertyDefinition.java:134)
        at com.miot.common.property.Property.setValue(Property.java:66)
        at com.miot.service.b.b.b.a(DecodeHelper.java:46)
        at com.miot.service.b.b.a.c.a(GetCodec.java:33)
        at com.miot.service.b.b.a(GetPropertyTask.java:50)
        at com.miot.service.b.b.parseResult(GetPropertyTask.java:23)
        at com.miot.service.common.d.e.run(MiotTask.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

定位到com.miot.common.device.parser.json.JsonDeviceParser中parseProperty()，在DataType.toObjectValue(String value)方法中是使用Double类型解析的，但是在AllowedValueRange中isValueValid中直接将Double强转成Float。所以出错了。

**Comment by wangchongwhut** [comment]
已修复。
